const guidePageList = [
    { name: "Button" },
    { name: "Card"  },
    { name: "Dialog" },
    { name: "Input" },
    { name: "Avatar" },
    { name: "Accordion" },
    { name: "AlertDialog" },
    { name: "AspectRatio" },
    { name: "Badge" },
    { name: "Breadcrumb" },
    { name: "ButtonGroup" },
    { name: "Calendar" },
    { name: "Carousel" },
    { name: "Chart" },
    { name: "Checkbox" },
    { name: "Combobox" },
    { name: "Command" },
    { name: "DataPicker" },
    { name: "DataTable" },
    { name: "Drawer" },
    { name: "DropdownMenu" },
    { name: "Empty" },
    { name: "Field" },
    { name: "Form" },
    { name: "HoverCard" },
  ];


export default guidePageList;